#!/usr/bin/env python3
"""Supplement table S5 of Paper A: total RBNS reserve error of the reproduction run by correction arm.

Inputs: results_v2/correction_comparison.csv (all objectives, arms none/paper/cv_global/cv_dy_bs1/cv_type_bs1/iso_global),
        results_cvz/correction_comparison.csv (the cross-validation-chosen shrinkage weight arm cv_dy_zcv, flagship only).
Output: paper/eaj/tables/table_s5_arms.tex. Rows: the leading configuration and the per-development-year two-stage
deviance-loss models. Values are total_reserve_error_pct, one decimal, '--' where an arm does not apply.
Usage: python tools/v2_arms_table.py
"""
import os, pandas as pd, numpy as np
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
def _first(*cands):
    for c in cands:
        if os.path.exists(c):
            return c
    raise FileNotFoundError(cands[0])


cc = pd.read_csv(_first(os.path.join(ROOT, "results_v2", "correction_comparison.csv"),
                     os.path.join(ROOT, "results", "correction_comparison.csv")))  # deposited layout of the public repository
if "cv_dy_zcv" in set(cc.arm):          # the matrix run computes the CV-Z arm itself
    cz = cc
else:                                    # older runs kept it in a separate directory
    cz = pd.read_csv(_first(os.path.join(ROOT, "results_cvz", "correction_comparison.csv"),
                            os.path.join(ROOT, "results", "cvz", "correction_comparison.csv")))
ROWS = [("random_forest__per_dy__log1p__two_stage", "Random forest, $\\log(1+y)$ target (leading configuration)"),
        ("random_forest_poisson__per_dy__raw__two_stage", "Random forest, Poisson split criterion"),
        ("hgb_poisson__per_dy__raw__two_stage", "Gradient boosting, Poisson deviance"),
        ("hgb_gamma__per_dy__raw__two_stage", "Gradient boosting, Gamma deviance"),
        ("lightgbm_poisson__per_dy__raw__two_stage", "LightGBM, Poisson deviance"),
        ("lightgbm_tweedie__per_dy__raw__two_stage", "LightGBM, Tweedie deviance")]
ARMS = ["none", "paper", "cv_global", "cv_dy_bs1", "cv_type_bs1", "cv_dy_zcv", "iso_global"]
HEAD = ["none", "heuristic", "global", "per DY, BS", "per type, BS", "per DY, CV-$Z$", "isotonic"]
def val(name, arm):
    if arm == "paper" and "log1p" not in name: return "--"
    src = cz if arm == "cv_dy_zcv" else cc
    r = src[(src.name == name) & (src.arm == arm)]
    if r.empty: return "--"
    v = float(r.total_reserve_error_pct.iloc[0])
    return f"${v:+.1f}$" if np.isfinite(v) and abs(v) < 1e4 else "--"
lines = [r"\begin{table}[ht]", r"\centering\footnotesize",
 r"\caption{Reproduction run of the leading configuration and of five deviance-loss models (all per development year,",
 r"two-stage): total RBNS reserve error (\%) by correction arm.  ``none'' is the raw pipeline output; ``heuristic'' the",
 r"calibration of the main text (only defined for the log target); ``global'' one cross-fitted ratio of the model's own development-year record (equal to the unshrunk per-DY factor); ``per DY, BS'' and",
 r"``per type, BS'' cross-fitted ratios per development year or claim type shrunk toward~1 with B\"uhlmann--Straub",
 r"weights; ``per DY, CV-$Z$'' per-DY ratios with a single shrinkage weight chosen by cross-validation on the aggregate",
 r"balance criterion); ``isotonic'' isotonic recalibration of the",
 r"predictions.  Generated by \texttt{tools/v2\_arms\_table.py} from the run outputs.}\label{tab:s5arms}",
 r"\setlength{\tabcolsep}{4pt}", r"\resizebox{\textwidth}{!}{%", r"\begin{tabular}{l" + "r" * len(ARMS) + "}", r"\toprule",
 "Model & " + " & ".join(HEAD) + r" \\", r"\midrule"]
for name, label in ROWS:
    lines.append(label + " & " + " & ".join(val(name, a) for a in ARMS) + r" \\")
lines += [r"\bottomrule", r"\end{tabular}}", r"\end{table}"]
OUT_DIR = os.path.join(ROOT, "paper", "eaj", "tables")
if not os.path.isdir(OUT_DIR):  # public mirror: no manuscript tree
    OUT_DIR = os.path.join(ROOT, "results", "tables"); os.makedirs(OUT_DIR, exist_ok=True)
out = os.path.join(OUT_DIR, "table_s5_arms.tex")
open(out, "w").write("\n".join(lines) + "\n"); print("wrote", out)
for name, _ in ROWS: print(name, [val(name, a) for a in ARMS])
